### ISSUE TITLE
Apache License vs. MIT License

### ISSUE THREAD

**Issue by kreuvf** [Lithl/lithl-snippets#1]
Your sheetworker-autocalc is licensed under the Apache License. In order to use it one has to incorporate the code into the Roll20 sheet worker scripts, which in turn have to be licensed under an MIT license for use on Roll20. That looks quite incompatible to me.

How to resolve this?

**Comment by Lithl** [comment]
You can use a component licensed under Apache 2 within software licensed under MIT so long as you include the Apache copyright notice and a notice of any changes you've made (if you've made any).

See https://www.whitesourcesoftware.com/whitesource-blog/top-10-apache-license-questions-answered/ for some good information, particularly points 1 and 6.

The licensing choice for this repo is non-negotiable, as it is a condition of my employer.

**Comment by kreuvf** [comment]
Thank you for the answer. Glad to hear that there are no issues. :+1:
